# Generated by Django 5.1 on 2024-10-01 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_fkuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
